### ISSUE TITLE
function cleanupWaypoints()

### ISSUE THREAD

**Issue by rhaschke** [ros-planning/moveit#1084]
To solve issue #737 in a clear fashion, I propose to add a utility function `cleanupWaypoints()` which can be called by time parameterization methods to remove identical consecutive waypoints.

**Comment by davetcoleman** [comment]
I'm not convinced we need such an over-engineered solution that will also increase computation time in planning. The previous simpler proposal https://github.com/ros-planning/moveit/pull/737 addressed the issue we actually found in the wild: duplicate starting point due to understandable misunderstanding of the API. If someone wants to implement this ``cleanupWaypoints()`` issue that is great, but someone may never actually do so and so, until then, https://github.com/ros-planning/moveit/pull/737 should be merged.
