### ISSUE TITLE
Unexpected rviz visualization for pandas robot executing panda_moveit_config demo

### ISSUE THREAD

**Issue by almartinflorido** [ros-planning/moveit#1333]
### Description

When I run the first demo [[1]](https://ros-planning.github.io/moveit_tutorials/doc/quickstart_in_rviz/quickstart_in_rviz_tutorial.html) of moveit tutorial, I don't see correctly the robot in RVIZ.

### Your environment
* ROS Distro: Melodic
* OS Version: Ubuntu 18.04
* Installation from packages, installation instructions: https://ros-planning.github.io/moveit_tutorials/doc/getting_started/getting_started.html

### Steps to reproduce

roslaunch panda_moveit_config demo.launch rviz_tutorial:=true

### Expected behaviour

![rviz_start](https://user-images.githubusercontent.com/12018634/52112809-f47d7500-2607-11e9-82bd-915950383091.png)

### Actual behaviour

![unexpected_visualization](https://user-images.githubusercontent.com/12018634/52112774-d748a680-2607-11e9-9180-e3f9aa60f78b.png)

### Backtrace or Console output

[rviz_log.txt](https://github.com/ros-planning/moveit/files/2820847/rviz_log.txt)

**Comment by gavanderhoorn** [comment]
Can you check whether this is the same problem as posted about in [MoveIt Tutorial - All Links at the same place!](https://answers.ros.org/question/314233) on ROS Answers?

**Comment by almartinflorido** [comment]
@gavanderhoorn You are right, I only added to my bashrc: 
`export LC_NUMERIC="en_US.UTF-8".`
and now it works!!!

thank you!!

**Comment by gavanderhoorn** [comment]
Please note that this is a *work around* and only needed because things like https://github.com/ros/urdfdom_headers/issues/45 and https://github.com/ros/urdfdom/issues/119 haven't been universally fixed yet.

Also note that setting that in your `.bashrc` will make it such that *all applications* will now use US English notation for numbers (ie: `,` vs `.`). Not necessarily what you'd want, depending on your language/region.
