### ISSUE TITLE
How to extract whole planner data using ompl as a plugin

### ISSUE THREAD

**Issue by hjw-1014** [ros-planning/moveit#2788]
Hi, I have a question but I'm so sure where can I ask for help, so I open an issue here, if it's not appropriate I will close then.

===============================================================================
For now, I useRRTstar in MoveIt for my robot (TIAGo++, which is a mobile manipulator) for base navigation. I wanna get the whole tree or all the information generated by the planners (In my case it's RRTstar), and then I will use this information for other random start states and generate a vector field based on the RRTstar tree.

I do notice there is a function `Show Exploration `in OMPL to show the positions of all the states generated by the planner, but I don't find any solutions that I can get the whole information if I just use MoveIt with OMPL plugin, cos I created a moveit_config for my robot, and modify the `move_froup_python_interface_tutorial.py` to plan. So my purpose is to use python code to get the planner data, like [here ](https://github.com/ompl/ompl/issues/374).

Because I met some errors when I installed ompl from source. I did install ompl using `sudo apt-get install ros-melodic-ompl`, but from my understanding, it's a plugin if I install `ompl `in this way. Then I still wanna install` ompl `as a package from source, like [here](https://ompl.kavrakilab.org/core/installation.html). I'm not sure if it's deprecated.

**So in my python file how can I get these paths or nodes in a matrix or .json, .csv, or in excel ?**
My moveit python file just like this: 
```
    move_group = MoveGroupPegInAHole()

    move_group.add_a_box()

    plan = move_group.joint_plan()
    if len(plan.joint_trajectory.points) !=0:
	move_group.save_in_json(plan)
    
    move_group.display_trajectory(plan)

    move_group.execute_plan(plan)

```
**I can get the final path, as mentioned above the variable `plan` and I also save it in` json`. But how to get the whole paths and nodes in MoveIt?**

My Env:
Ubuntu 18.04
ROS melodic

Thanks in advance

**Comment by felixvd** [comment]
The intermediate planning results are not passed to the MoveIt plugin, only the resulting path is. Judging by the thread you linked, you will need to modify OMPL with some custom code to output the data you need, so this is not a MoveIt issue. You will need to build OMPL from source after you modify it.

> Because I met some errors when I installed ompl from source. I did install ompl using `sudo apt-get install ros-melodic-ompl`, but from my understanding, it's a plugin if I install `ompl` in this way. Then I still wanna install `ompl` as a package from source, like here. I'm not sure if it's deprecated.

Just for the record, since there seems to be confusion about the terms: you obtain the OMPL binaries, regardless if you install from the package repository (`sudo apt-get install ros-melodic-ompl`) or you build from source. There is a MoveIt plugin that uses the OMPL binaries (the OMPL C++ functions and API) to obtain a path by translating to and from the MoveIt data structures. OMPL itself is not a plugin.

I will close this since this seems to be related to OMPL.
