### ISSUE TITLE
Fix clang-tidy and use optimizations

### ISSUE THREAD

**Issue by tylerjw** [ros-planning/moveit#2809]
### Description

https://github.com/ros-planning/moveit/pull/2792  Changes the optimization level of one package to fix a clang-tidy issue.  This seems gross to me and we should be able to figure out another way of fixing this.

**Comment by v4hn** [comment]
it's worse than gross because the file is at the core of collision checking with FCL. So the slowdown is probably quite big.

The issue is not with clang-tidy though. 
It's that building `libmoveit_collision_detection_fcl.so` with clang produces invalid code and we recently added a test that points this out.
