### ISSUE TITLE
How to use moveit IK with Xarm6

### ISSUE THREAD

**Issue by Aki92-Xavier** [ros-planning/moveit#2873]
Hi, now I'm trying to use IK on Xarm6 but i couldn't find how to do it.
I'm using Realsense D435 to get the [x,y,z] and move the arm to that target value.

**Comment by felixvd** [comment]
This Github repository is for technical issues, bugs and improvements regarding MoveIt. Please use [ROS Answers](https://answers.ros.org) for usage questions.

In addition, please provide more detail about what you have attempted, as described in the [question guidelines](https://answers.ros.org/questions/ask/) on ROS Answers. [This tutorial](https://ros-planning.github.io/moveit_tutorials/doc/move_group_interface/move_group_interface_tutorial.html#enforce-planning-in-joint-space) shows a way to set robot joint angles from IK.

I am closing this because I have used an Xarm6 with a Realsense D435 before without issue.
