### ISSUE TITLE
upgrade of packages in docker image?

### ISSUE THREAD

**Issue by rhaschke** [ros-planning/moveit#322]
Shouldn't the move_ci script upgrade installed packages in a docker image? [Currently, there is only an update command. ](https://github.com/ros-planning/moveit_ci/blob/master/travis.sh#L77)

To get a new package release into our travis, we need to manually trigger a corresponding Docker build, don't we?

**Comment by davetcoleman** [comment]
I documented this [here](http://moveit.ros.org/documentation/contributing/continuous_integration/):

> We use Dockerhub to automatically build new versions of the containers each time a code change is committed to the moveit repo (but only for the corresponding branch).

The only caveat is that if we don't change the code base for a long time, there is a potential for the next pull request to be tested on an old version of ROS. But our containers also update everytime there is an Ubuntu update because our container builds on top of Ubuntu containers, so it will be triggered then too (every few weeks)
