### ISSUE TITLE
unable to sample any valid states for goal tree

### ISSUE THREAD

**Issue by shixinlishixinli** [ros-planning/moveit#343]
hi,i am using indigo and my own urdf , and i use setPoseTarget().sometimes it can plan and execute ,sometimes it can not .my arm is 4 dof arm but i am sure my moveit is update.
![1](https://cloud.githubusercontent.com/assets/20768380/20163506/06109280-a738-11e6-8946-df6c5533d3ad.png)
![screenshot from 2016-11-10 11 06 18](https://cloud.githubusercontent.com/assets/20768380/20163507/0df9ce4e-a738-11e6-9647-a8336b8a8a40.png)

**Comment by v4hn** [comment]
This is far too unspecific to help you.

- Does plan&execute work in rviz?
- Are you sure your PoseTarget is reachable?
- What exactly does your "test_custom_node" do
- What's up with these warnings about orientation constraints?

**Comment by shixinlishixinli** [comment]
plan and execute is work in rviz and pose target is reachable ,my test_custom is publish a poestion and oritation

**Comment by shixinlishixinli** [comment]
i am not sure is there any reason about my arm is 4 dof

**Comment by v4hn** [comment]
Sorry for the long delay. Is this still relevant? Otherwise I would close this for now...

Planning works in RViz because the rviz plugin already performs inverse kinematics(IK) for your target pose and you simply cannot press the planning button if you don't see the goal joint configuration (in yellow/orange) in the visualization.

There are a number of problems with IK for arms that do not have exactly 6 or 7 DoF
and KDL (I assume this is your selected IK plugin as you didn't mention you use a different one) often fails to find solutions here.
If you can do that, it might be worth a try to generate an IK-fast plugin for your specific robot.
