### ISSUE TITLE
Unable to sample any valid states for goal tree after change of planning frame

### ISSUE THREAD

**Issue by Akumar201** [ros-planning/moveit#3567]
I am trying to move the robotic arm by 1 cm from it's current value  using following code , when I use planning frame as top I am getting an error while when I use it as world it plans and execute successfully. I am also attaching robot_macro.xacro

I am pretty sure that there is no collision happening but feels like something is wrong with the transformation. Explanation of desired result -  I want to use aruco on a board above the ground names as "top" and use that as frame of reference to move the arm 

    #!/usr/bin/env python
    
    import rospy import sys import moveit_commander from geometry_msgs.msg import Pose, PoseStamped
    
    def move_arm():
        rospy.init_node('move_arm_node', anonymous=True)
        
        # Initialize MoveIt
        moveit_commander.roscpp_initialize(sys.argv)
        robot = moveit_commander.RobotCommander()
        group_name = "arm6"  # specify the name of your arm planning group
        move_group = moveit_commander.MoveGroupCommander(group_name)
    
        # Get the current pose
        current_pose = move_group.get_current_pose().pose
        rospy.loginfo("Current Pose: \n{}".format(current_pose))
        
        # Calculate the desired pose
        desired_pose = Pose()
        desired_pose.position.x = current_pose.position.x   # Move 1 cm in the X direction
        desired_pose.position.y = current_pose.position.y - 0.001
        desired_pose.position.z = current_pose.position.z
        desired_pose.orientation = current_pose.orientation  # Maintain the same orientation
        
        # Set the target pose
        target_pose = PoseStamped()
        target_pose.header.frame_id = "top_plate"  # specify your planning frame
        target_pose.pose = desired_pose
    
        # Set the target pose for the end-effector
        move_group.set_pose_target(target_pose)
        
        # Plan and execute the trajectory
        move_group.go(wait=True)
    
    if __name__ == '__main__':
        try:
            move_arm()
        except rospy.ROSInterruptException:
            pass

**xacro**

    <link name="top">
      <visual>
        <geometry>
          <box size="0.78899 0.60325 0.025652"/> 
        </geometry>
        <material name="Grey">
                <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
        <origin xyz="0 0 0" rpy="0 0 0"/> 
      </visual>

        
      <collision>
        <geometry>
          <box size="0.78899 0.60325 0.025652"/> 
        </geometry>
      </collision>
    </link>

    <joint name="top" type="fixed">
        <parent link="world" />
        <child link="top" />
        <origin xyz="0 0.1778 0.554019" rpy="0 0 0" />
    </joint>

**Comment by memejang** [comment]
What's the problem with conversion?

**Comment by devika-dudo** [comment]
I am able to plan and execute a particular xyz and orientation in rviz but when i tried to run a cpp node with the same I am getting the same error, can you explain what you did?

**Comment by Vihaan30g** [comment]
I am still facing this issue after trying most of the commonly suggested solutions from existing online discussions (reachable pose verification, increasing target pose precision, relaxing constraints, changing IK solvers, etc.).

To make debugging easier, I created a minimal reproducible workspace and uploaded it here:

**Repository:**
https://github.com/Vihaan30g/ws_manip

The repository contains the complete workspace required to reproduce the issue. Mesh files have been removed because they are part of our team's custom manipulator design, but the URDF/Xacro files, MoveIt configuration, launch files, and scripts are included so that the software setup can be fully inspected and debugged.

## How I run the system

### Terminal 1

```bash
ros2 launch moveit_pkg2 ignition_sim.launch.py
```

### Terminal 2

```bash
ros2 launch moveit_pkg2 moveit.launch.py
```

### Then

```bash
python3 src/direct_move.py
```

The planning request is sent through `src/direct_move.py`.

The target pose used in the script was obtained from the robot's current valid end-effector pose using `tf2_echo`, so it should be reachable.

However, planning consistently fails with:

```text
Unable to sample any valid states for goal tree
```

Relevant log output:

```text
[ERROR] [ompl]: body/body: Unable to sample any valid states for goal tree
[WARN] [ompl]: ParallelPlan::solve(): Unable to find solution by any of the threads in 5.002358 seconds
[INFO] [moveit.ompl_planning.model_based_planning_context]: Unable to solve the planning problem
[INFO] [moveit_move_group_default_capabilities.move_action_capability]: Catastrophic failure
```

### Additional Observation

If I manually drag the end-effector using the RViz interactive marker and click **"Plan and Execute"**, MoveIt plans and executes successfully.

The problem only appears when I try to send a target pose programmatically through the Python script.

I would appreciate any suggestions on what I may have overlooked. If anyone is willing to inspect the workspace in more detail, the repository above contains everything needed to reproduce the issue.

**Comment by Flamethr0wer** [comment]
@Vihaan30g It seems you have the same problem I described [here](https://github.com/AndrejOrsula/pymoveit2/issues/103#issuecomment-3032209686); Rviz supports approximate IK solutions, but otherwise they are disabled by default. Especially with lower-DOF robots, a non-approximate solution may be impossible and in that case it will fail with that exact output. I managed to solve this by going to [kinematics_base.h](https://github.com/moveit/moveit/blob/master/moveit_core/kinematics_base/include/moveit/kinematics_base/kinematics_base.h) and setting the default value for `return_approximate_solution` to `true`. See if that works for you.

**Comment by Vihaan30g** [comment]
@Flamethr0wer
Yes, your suggested solution worked.
This issue had been troubling me for quite a while, and I had spent a lot of time trying to debug it. 
Thank you so much for your help.

**Comment by Flamethr0wer** [comment]
Glad I could help ;D
