### ISSUE TITLE
MSA: consider using `xacro --in-order` on Indigo as well?

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-planning/moveit#511]
`xacro` supports Jade+-like parsing of xacros on Indigo, but the Setup Assistant doesn't use this. This leads to the situation where xacros that load perfectly fine when `xacro` is invoked / used stand-alone to not load in the MSA.

Would it be an idea to have Indigo MSA add the `--in-order` argument ([here](https://github.com/ros-planning/moveit/blob/fb2ebe3826e8d2b15dc99188343fc0cf2b3dc939/moveit_setup_assistant/src/widgets/start_screen_widget.cpp#L508)) so that we get Jade+ xacro parsing? Should this be an option (ie: check box)?

**Comment by v4hn** [comment]
On Mon, May 22, 2017 at 12:26:58PM -0700, G.A. vd. Hoorn wrote:
> `xacro` supports Jade+-like parsing of xacros on Indigo, but the Setup Assistant doesn't use this. This leads to the situation where xacros that load perfectly fine when `xacro` is invoked / used stand-alone to not load in the MSA.
> 
> Would it be an idea to have Indigo MSA add the `--in-order` argument ([here](https://github.com/ros-planning/moveit/blob/fb2ebe3826e8d2b15dc99188343fc0cf2b3dc939/moveit_setup_assistant/src/widgets/start_screen_widget.cpp#L508)) so that we get Jade+ xacro parsing? Should this be an option (ie: check box)?

I believe changing the default in indigo in not an option because in-order parsing can also break xacros that work well in current indigo.
That being said, I would support a check-box and/or an item in `.setup_assistant` to address this.

**Comment by gavanderhoorn** [comment]
A checkbox is a good idea. I'll see if I can implement that.

**Comment by gavanderhoorn** [comment]
Although #540 is merged, I'll keep this open as the command line interface to the MSA needs to be checked for support of this.

**Comment by ipa-fxm** [comment]
Though the new checkbox works great when `Create New Moveit Configuration Package` is selected, unfortunately, it fails to load the xacro (which uses Jade+ features) when `Edit Existing Moveit Configuration Package` is selected.

**Comment by gavanderhoorn** [comment]
@ipa-fxm: see the discussion on the #540 for why we didn't add the checkbox to the *Edit existing package* UI.

**Comment by bmagyar** [comment]
+1

**Comment by gavanderhoorn** [comment]
@bmagyar: what are you `+1`-ing specifically? :)

**Comment by bmagyar** [comment]
My bad,  I haven't seen your response ;)

I do agree with the need Felix expressed, I had issues with that years
ago...

On Oct 23, 2017 9:02 AM, "G.A. vd. Hoorn" <notifications@github.com> wrote:

@bmagyar <https://github.com/bmagyar>: what are you +1-ing specifically? :)

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/ros-planning/moveit/issues/511#issuecomment-338578592>,
or mute the thread

**Comment by v4hn** [comment]
closing as outdated
