### ISSUE TITLE
CHOMP: Optimizer not initializing

### ISSUE THREAD

**Issue by angadhn** [ros-planning/moveit#770]
### Description
Hi folks,

I am following the instructions to test out CHOMP based on the [CHOMP interface tutorial on the kinetic moveit docs](http://docs.ros.org/kinetic/api/moveit_tutorials/html/doc/chomp_interface_tutorial.html). However, I get the following error:
```bash
[ERROR] [1518709837.241774873]: Could not initialize optimizer
```
Any suggestions on getting past this would be much appreciated.

### Your environment
* Kinetic
* Ubuntu 16.04
* Source build: kinetic-devel

### Steps to reproduce
1. cloned the kinetic-devel branch in ```catkin_ws/src``` by:
```git clone https://github.com/ros-planning/moveit.git```.
2. built with ```catkin_make```. 
3. ```roslaunch moveit_resources demo_chomp.launch``` launches RViz with the motion planning plugin.
4. Under the planning tab, I select a 'random valid' goal state and then 'Update' followd by Plan.

### Expected behaviour
A successful motion execute by the robot: Robot moves to valid goal state based on the plan generated by CHOMP.

### Actual behaviour
Planner fails and I get the message that the optimizer could not be initialized.

### Backtrace or Console output
```
started roslaunch server http://alienware2:37799/

SUMMARY
========

PARAMETERS
 * /joint_state_publisher/use_gui: False
 * /move_group/allow_trajectory_execution: True
 * /move_group/capabilities: move_group/MoveGr...
 * /move_group/controller_list: [{'joints': ['joi...
 * /move_group/jiggle_fraction: 0.05
 * /move_group/max_range: 5.0
 * /move_group/max_safe_path_cost: 1
 * /move_group/moveit_controller_manager: moveit_fake_contr...
 * /move_group/moveit_manage_controllers: True
 * /move_group/octomap_resolution: 0.025
 * /move_group/planning_plugin: chomp_interface/C...
 * /move_group/planning_scene_monitor/publish_geometry_updates: True
 * /move_group/planning_scene_monitor/publish_planning_scene: True
 * /move_group/planning_scene_monitor/publish_state_updates: True
 * /move_group/planning_scene_monitor/publish_transforms_updates: True
 * /move_group/start_state_max_bounds_error: 0.1
 * /move_group/trajectory_execution/allowed_execution_duration_scaling: 1.2
 * /move_group/trajectory_execution/allowed_goal_duration_margin: 0.5
 * /robot_description: <?xml version="1....
 * /robot_description_kinematics/manipulator/kinematics_solver: kdl_kinematics_pl...
 * /robot_description_kinematics/manipulator/kinematics_solver_attempts: 3
 * /robot_description_kinematics/manipulator/kinematics_solver_search_resolution: 0.005
 * /robot_description_kinematics/manipulator/kinematics_solver_timeout: 0.005
 * /robot_description_planning/joint_limits/joint_1/has_acceleration_limits: True
 * /robot_description_planning/joint_limits/joint_1/has_velocity_limits: True
 * /robot_description_planning/joint_limits/joint_1/max_acceleration: 0.734
 * /robot_description_planning/joint_limits/joint_1/max_velocity: 3.67
 * /robot_description_planning/joint_limits/joint_2/has_acceleration_limits: True
 * /robot_description_planning/joint_limits/joint_2/has_velocity_limits: True
 * /robot_description_planning/joint_limits/joint_2/max_acceleration: 0.664
 * /robot_description_planning/joint_limits/joint_2/max_velocity: 3.32
 * /robot_description_planning/joint_limits/joint_3/has_acceleration_limits: True
 * /robot_description_planning/joint_limits/joint_3/has_velocity_limits: True
 * /robot_description_planning/joint_limits/joint_3/max_acceleration: 0.734
 * /robot_description_planning/joint_limits/joint_3/max_velocity: 3.67
 * /robot_description_planning/joint_limits/joint_4/has_acceleration_limits: True
 * /robot_description_planning/joint_limits/joint_4/has_velocity_limits: True
 * /robot_description_planning/joint_limits/joint_4/max_acceleration: 1.396
 * /robot_description_planning/joint_limits/joint_4/max_velocity: 6.98
 * /robot_description_planning/joint_limits/joint_5/has_acceleration_limits: True
 * /robot_description_planning/joint_limits/joint_5/has_velocity_limits: True
 * /robot_description_planning/joint_limits/joint_5/max_acceleration: 1.396
 * /robot_description_planning/joint_limits/joint_5/max_velocity: 6.98
 * /robot_description_planning/joint_limits/joint_6/has_acceleration_limits: True
 * /robot_description_planning/joint_limits/joint_6/has_velocity_limits: True
 * /robot_description_planning/joint_limits/joint_6/max_acceleration: 2.094
 * /robot_description_planning/joint_limits/joint_6/max_velocity: 10.47
 * /robot_description_semantic: <?xml version="1....
 * /rosdistro: kinetic
 * /rosversion: 1.12.12
 * /rviz_alienware2_14938_2640807834323889303/manipulator/kinematics_solver: kdl_kinematics_pl...
 * /rviz_alienware2_14938_2640807834323889303/manipulator/kinematics_solver_attempts: 3
 * /rviz_alienware2_14938_2640807834323889303/manipulator/kinematics_solver_search_resolution: 0.005
 * /rviz_alienware2_14938_2640807834323889303/manipulator/kinematics_solver_timeout: 0.005
 * /source_list: ['/move_group/fak...

NODES
  /
    joint_state_publisher (joint_state_publisher/joint_state_publisher)
    move_group (moveit_ros_move_group/move_group)
    robot_state_publisher (robot_state_publisher/robot_state_publisher)
    rviz_alienware2_14938_2640807834323889303 (rviz/rviz)

auto-starting new master
process[master]: started with pid [14948]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to dbae840c-126b-11e8-bcfe-9cb6d061e4ff
process[rosout-1]: started with pid [14961]
started core service [/rosout]
process[joint_state_publisher-2]: started with pid [14978]
process[robot_state_publisher-3]: started with pid [14979]
process[move_group-4]: started with pid [14980]
process[rviz_alienware2_14938_2640807834323889303-5]: started with pid [14982]
[ INFO] [1518711509.781723346]: Loading robot model 'fanuc'...
[ INFO] [1518711509.812947850]: Loading robot model 'fanuc'...
[ INFO] [1518711509.834380533]: rviz version 1.12.15
[ INFO] [1518711509.834440816]: compiled against Qt version 5.5.1
[ INFO] [1518711509.834454926]: compiled against OGRE version 1.9.0 (Ghadamon)
[ INFO] [1518711509.872675061]: Publishing maintained planning scene on 'monitored_planning_scene'
[ INFO] [1518711509.875144787]: MoveGroup debug mode is ON
Starting context monitors...
[ INFO] [1518711509.875185682]: Starting scene monitor
[ INFO] [1518711509.877766841]: Listening to '/planning_scene'
[ INFO] [1518711509.877815793]: Starting world geometry monitor
[ INFO] [1518711509.880707359]: Listening to '/collision_object' using message notifier with target frame '/base_link '
[ INFO] [1518711509.883035798]: Listening to '/planning_scene_world' for planning scene world geometry
[ INFO] [1518711509.896102649]: Listening to '/attached_collision_object' for attached collision objects
Context monitors started.
[ INFO] [1518711509.902157120]: Following groups exist:
[ INFO] [1518711509.902208195]: manipulator
[ INFO] [1518711509.912721255]: Configuring New Planning Scene.
[ INFO] [1518711510.127992334]: Using planning interface 'CHOMP'
[ INFO] [1518711510.135037899]: Fake controller 'fake_manipulator_controller' with joints [ joint_1 joint_2 joint_3 joint_4 joint_5 joint_6 ]
[ INFO] [1518711510.135555628]: Returned 1 controllers in list
[ INFO] [1518711510.147101814]: Trajectory execution is managing controllers
Loading 'move_group/ApplyPlanningSceneService'...
Loading 'move_group/ClearOctomapService'...
Loading 'move_group/MoveGroupCartesianPathService'...
Loading 'move_group/MoveGroupExecuteService'...
Loading 'move_group/MoveGroupExecuteTrajectoryAction'...
Loading 'move_group/MoveGroupGetPlanningSceneService'...
Loading 'move_group/MoveGroupKinematicsService'...
Loading 'move_group/MoveGroupMoveAction'...
Loading 'move_group/MoveGroupPickPlaceAction'...
Loading 'move_group/MoveGroupPlanService'...
Loading 'move_group/MoveGroupQueryPlannersService'...
Loading 'move_group/MoveGroupStateValidationService'...
[ INFO] [1518711510.223779180]: 

********************************************************
* MoveGroup using: 
*     - ApplyPlanningSceneService
*     - ClearOctomapService
*     - CartesianPathService
*     - ExecuteTrajectoryService
*     - ExecuteTrajectoryAction
*     - GetPlanningSceneService
*     - KinematicsService
*     - MoveAction
*     - PickPlaceAction
*     - MotionPlanService
*     - QueryPlannersService
*     - StateValidationService
********************************************************

[ INFO] [1518711510.223854936]: MoveGroup context using planning plugin chomp_interface/CHOMPPlanner
[ INFO] [1518711510.223887397]: MoveGroup context initialization complete

You can start planning now!

[ INFO] [1518711510.415241793]: Stereo is NOT SUPPORTED
[ INFO] [1518711510.415335904]: OpenGl version: 4.5 (GLSL 4.5).
[ INFO] [1518711513.717262871]: Loading robot model 'fanuc'...
[ INFO] [1518711513.750098155]: Loading robot model 'fanuc'...
[ INFO] [1518711513.844775686]: Starting scene monitor
[ INFO] [1518711513.848521576]: Listening to '/move_group/monitored_planning_scene'
[ INFO] [1518711513.918323640]: Constructing new MoveGroup connection for group 'manipulator' in namespace ''
[ WARN] [1518711514.868835457]: 
Deprecation warning: Trajectory execution service is deprecated (was replaced by an action).
Replace 'MoveGroupExecuteService' with 'MoveGroupExecuteTrajectoryAction' in move_group.launch
[ INFO] [1518711514.881028235]: Ready to take commands for planning group manipulator.
[ INFO] [1518711514.881208561]: Looking around: no
[ INFO] [1518711514.881296407]: Replanning: no
[ INFO] [1518711673.516395573]: Planning request received for MoveGroup action. Forwarding to planning pipeline.
[ INFO] [1518711673.521698036]: Setting joint joint_1 to position -0.381429
[ INFO] [1518711673.521805199]: Setting joint joint_2 to position -0.957978
[ INFO] [1518711673.521862023]: Setting joint joint_3 to position -0.889114
[ INFO] [1518711673.521952940]: Setting joint joint_4 to position 0.783808
[ INFO] [1518711673.522011248]: Setting joint joint_5 to position -1.56329
[ INFO] [1518711673.522067221]: Setting joint joint_6 to position -3.64563
[ INFO] [1518711673.524336845]: The following collision detectors are active in the planning scene.
[ INFO] [1518711673.524401001]: FCL
[ INFO] [1518711673.524464391]: Active collision detector is: FCL
[ WARN] [1518711673.524515991]: Could not initialize hybrid collision world from planning scene
[ERROR] [1518711673.524567754]: Could not initialize optimizer
[ WARN] [1518711673.552247080]: Fail: ABORTED: No motion plan found. No execution attempted.
```
Use [gist.github.com](gist.github.com) to copy-paste the console output or segfault backtrace using gdb.

**Comment by bmagyar** [comment]
This may have been my last PR. I'll check this weekend!

On Feb 15, 2018 16:22, "Angadh Nanjangud" <notifications@github.com> wrote:

Description

Hi folks,

I am following the instructions to test out CHOMP based on the interface
tutorial on moveit docs. However, I get the following error:

[ERROR] [1518709837.241774873]: Could not initialize optimizer

Any suggestions on getting past this would be much appreciated.
Your environment

   - Kinetic
   - Ubuntu 16.04
   - Source build: kinetic-devel

Steps to reproduce

   1. cloned the kinetic-devel branch in catkin_ws/src by:
   git clone https://github.com/ros-planning/moveit.git.
   2. built with catkin_make.
   3. roslaunch moveit_resources demo_chomp.launch launches RViz with the
   motion planning plugin.
   4. Under the planning tab, I select a 'random valid' goal state and then
   'Update' followd by Plan.

Expected behaviour

A successful motion execute by the robot: Robot moves to valid goal state
based on the plan generated by CHOMP.
Actual behaviour

Planner fails and I get the message that the optimizer could not be
initialized.
Backtrace or Console output

started roslaunch server http://alienware2:37799/

SUMMARY
========

PARAMETERS
 * /joint_state_publisher/use_gui: False
 * /move_group/allow_trajectory_execution: True
 * /move_group/capabilities: move_group/MoveGr...
 * /move_group/controller_list: [{'joints': ['joi...
 * /move_group/jiggle_fraction: 0.05
 * /move_group/max_range: 5.0
 * /move_group/max_safe_path_cost: 1
 * /move_group/moveit_controller_manager: moveit_fake_contr...
 * /move_group/moveit_manage_controllers: True
 * /move_group/octomap_resolution: 0.025
 * /move_group/planning_plugin: chomp_interface/C...
 * /move_group/planning_scene_monitor/publish_geometry_updates: True
 * /move_group/planning_scene_monitor/publish_planning_scene: True
 * /move_group/planning_scene_monitor/publish_state_updates: True
 * /move_group/planning_scene_monitor/publish_transforms_updates: True
 * /move_group/start_state_max_bounds_error: 0.1
 * /move_group/trajectory_execution/allowed_execution_duration_scaling: 1.2
 * /move_group/trajectory_execution/allowed_goal_duration_margin: 0.5
 * /robot_description: <?xml version="1....
 * /robot_description_kinematics/manipulator/kinematics_solver:
kdl_kinematics_pl...
 * /robot_description_kinematics/manipulator/kinematics_solver_attempts: 3
 * /robot_description_kinematics/manipulator/kinematics_solver_search_resolution:
0.005
 * /robot_description_kinematics/manipulator/kinematics_solver_timeout: 0.005
 * /robot_description_planning/joint_limits/joint_1/has_acceleration_limits:
True
 * /robot_description_planning/joint_limits/joint_1/has_velocity_limits: True
 * /robot_description_planning/joint_limits/joint_1/max_acceleration: 0.734
 * /robot_description_planning/joint_limits/joint_1/max_velocity: 3.67
 * /robot_description_planning/joint_limits/joint_2/has_acceleration_limits:
True
 * /robot_description_planning/joint_limits/joint_2/has_velocity_limits: True
 * /robot_description_planning/joint_limits/joint_2/max_acceleration: 0.664
 * /robot_description_planning/joint_limits/joint_2/max_velocity: 3.32
 * /robot_description_planning/joint_limits/joint_3/has_acceleration_limits:
True
 * /robot_description_planning/joint_limits/joint_3/has_velocity_limits: True
 * /robot_description_planning/joint_limits/joint_3/max_acceleration: 0.734
 * /robot_description_planning/joint_limits/joint_3/max_velocity: 3.67
 * /robot_description_planning/joint_limits/joint_4/has_acceleration_limits:
True
 * /robot_description_planning/joint_limits/joint_4/has_velocity_limits: True
 * /robot_description_planning/joint_limits/joint_4/max_acceleration: 1.396
 * /robot_description_planning/joint_limits/joint_4/max_velocity: 6.98
 * /robot_description_planning/joint_limits/joint_5/has_acceleration_limits:
True
 * /robot_description_planning/joint_limits/joint_5/has_velocity_limits: True
 * /robot_description_planning/joint_limits/joint_5/max_acceleration: 1.396
 * /robot_description_planning/joint_limits/joint_5/max_velocity: 6.98
 * /robot_description_planning/joint_limits/joint_6/has_acceleration_limits:
True
 * /robot_description_planning/joint_limits/joint_6/has_velocity_limits: True
 * /robot_description_planning/joint_limits/joint_6/max_acceleration: 2.094
 * /robot_description_planning/joint_limits/joint_6/max_velocity: 10.47
 * /robot_description_semantic: <?xml version="1....
 * /rosdistro: kinetic
 * /rosversion: 1.12.12
 * /rviz_alienware2_14938_2640807834323889303/manipulator/kinematics_solver:
kdl_kinematics_pl...
 * /rviz_alienware2_14938_2640807834323889303/manipulator/kinematics_solver_attempts:
3
 * /rviz_alienware2_14938_2640807834323889303/manipulator/kinematics_solver_search_resolution:
0.005
 * /rviz_alienware2_14938_2640807834323889303/manipulator/kinematics_solver_timeout:
0.005
 * /source_list: ['/move_group/fak...

NODES
  /
    joint_state_publisher (joint_state_publisher/joint_state_publisher)
    move_group (moveit_ros_move_group/move_group)
    robot_state_publisher (robot_state_publisher/robot_state_publisher)
    rviz_alienware2_14938_2640807834323889303 (rviz/rviz)

auto-starting new master
process[master]: started with pid [14948]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to dbae840c-126b-11e8-bcfe-9cb6d061e4ff
process[rosout-1]: started with pid [14961]
started core service [/rosout]
process[joint_state_publisher-2]: started with pid [14978]
process[robot_state_publisher-3]: started with pid [14979]
process[move_group-4]: started with pid [14980]
process[rviz_alienware2_14938_2640807834323889303-5]: started with pid [14982]
[ INFO] [1518711509.781723346]: Loading robot model 'fanuc'...
[ INFO] [1518711509.812947850]: Loading robot model 'fanuc'...
[ INFO] [1518711509.834380533]: rviz version 1.12.15
[ INFO] [1518711509.834440816]: compiled against Qt version 5.5.1
[ INFO] [1518711509.834454926]: compiled against OGRE version 1.9.0 (Ghadamon)
[ INFO] [1518711509.872675061]: Publishing maintained planning scene
on 'monitored_planning_scene'
[ INFO] [1518711509.875144787]: MoveGroup debug mode is ON
Starting context monitors...
[ INFO] [1518711509.875185682]: Starting scene monitor
[ INFO] [1518711509.877766841]: Listening to '/planning_scene'
[ INFO] [1518711509.877815793]: Starting world geometry monitor
[ INFO] [1518711509.880707359]: Listening to '/collision_object' using
message notifier with target frame '/base_link '
[ INFO] [1518711509.883035798]: Listening to '/planning_scene_world'
for planning scene world geometry
[ INFO] [1518711509.896102649]: Listening to
'/attached_collision_object' for attached collision objects
Context monitors started.
[ INFO] [1518711509.902157120]: Following groups exist:
[ INFO] [1518711509.902208195]: manipulator
[ INFO] [1518711509.912721255]: Configuring New Planning Scene.
[ INFO] [1518711510.127992334]: Using planning interface 'CHOMP'
[ INFO] [1518711510.135037899]: Fake controller
'fake_manipulator_controller' with joints [ joint_1 joint_2 joint_3
joint_4 joint_5 joint_6 ]
[ INFO] [1518711510.135555628]: Returned 1 controllers in list
[ INFO] [1518711510.147101814]: Trajectory execution is managing controllers
Loading 'move_group/ApplyPlanningSceneService'...
Loading 'move_group/ClearOctomapService'...
Loading 'move_group/MoveGroupCartesianPathService'...
Loading 'move_group/MoveGroupExecuteService'...
Loading 'move_group/MoveGroupExecuteTrajectoryAction'...
Loading 'move_group/MoveGroupGetPlanningSceneService'...
Loading 'move_group/MoveGroupKinematicsService'...
Loading 'move_group/MoveGroupMoveAction'...
Loading 'move_group/MoveGroupPickPlaceAction'...
Loading 'move_group/MoveGroupPlanService'...
Loading 'move_group/MoveGroupQueryPlannersService'...
Loading 'move_group/MoveGroupStateValidationService'...
[ INFO] [1518711510.223779180]:

********************************************************
* MoveGroup using:
*     - ApplyPlanningSceneService
*     - ClearOctomapService
*     - CartesianPathService
*     - ExecuteTrajectoryService
*     - ExecuteTrajectoryAction
*     - GetPlanningSceneService
*     - KinematicsService
*     - MoveAction
*     - PickPlaceAction
*     - MotionPlanService
*     - QueryPlannersService
*     - StateValidationService
********************************************************

[ INFO] [1518711510.223854936]: MoveGroup context using planning
plugin chomp_interface/CHOMPPlanner
[ INFO] [1518711510.223887397]: MoveGroup context initialization complete

You can start planning now!

[ INFO] [1518711510.415241793]: Stereo is NOT SUPPORTED
[ INFO] [1518711510.415335904]: OpenGl version: 4.5 (GLSL 4.5).
[ INFO] [1518711513.717262871]: Loading robot model 'fanuc'...
[ INFO] [1518711513.750098155]: Loading robot model 'fanuc'...
[ INFO] [1518711513.844775686]: Starting scene monitor
[ INFO] [1518711513.848521576]: Listening to
'/move_group/monitored_planning_scene'
[ INFO] [1518711513.918323640]: Constructing new MoveGroup connection
for group 'manipulator' in namespace ''
[ WARN] [1518711514.868835457]:
Deprecation warning: Trajectory execution service is deprecated (was
replaced by an action).
Replace 'MoveGroupExecuteService' with
'MoveGroupExecuteTrajectoryAction' in move_group.launch
[ INFO] [1518711514.881028235]: Ready to take commands for planning
group manipulator.
[ INFO] [1518711514.881208561]: Looking around: no
[ INFO] [1518711514.881296407]: Replanning: no
[ INFO] [1518711673.516395573]: Planning request received for
MoveGroup action. Forwarding to planning pipeline.
[ INFO] [1518711673.521698036]: Setting joint joint_1 to position -0.381429
[ INFO] [1518711673.521805199]: Setting joint joint_2 to position -0.957978
[ INFO] [1518711673.521862023]: Setting joint joint_3 to position -0.889114
[ INFO] [1518711673.521952940]: Setting joint joint_4 to position 0.783808
[ INFO] [1518711673.522011248]: Setting joint joint_5 to position -1.56329
[ INFO] [1518711673.522067221]: Setting joint joint_6 to position -3.64563
[ INFO] [1518711673.524336845]: The following collision detectors are
active in the planning scene.
[ INFO] [1518711673.524401001]: FCL
[ INFO] [1518711673.524464391]: Active collision detector is: FCL
[ WARN] [1518711673.524515991]: Could not initialize hybrid collision
world from planning scene
[ERROR] [1518711673.524567754]: Could not initialize optimizer
[ WARN] [1518711673.552247080]: Fail: ABORTED: No motion plan found.
No execution attempted.

Use gist.github.com to copy-paste the console output or segfault backtrace
using gdb.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ros-planning/moveit/issues/770>, or mute the thread

**Comment by angadhn** [comment]
No worries; this is just an issue with the demo setup; I got the motion planner working with my UR5 no problem. However, I need to work out why the executed trajectory of the real robot is so jerky when compared to the plan shown on rviz. While I don't think this is necessarily a CHOMP issue, the execution does seem smoother with OMPL planners. I'll have to take a look at it tomorrow morning but any suggestions are welcome :)

**Comment by bmagyar** [comment]
UR5-s have limits on velocities and accelerations enforced by the control
box. That may be one thing.

Out of curiosity: could you post here some videos of the jerky vs normal
trajectories please?

You could also compare the trajectory sampling rate for the 2 different
planners, CHOMP may do a higher rate sampling which'd force more aggressive
behaviours on the controller.

**Comment by angadhn** [comment]
Will do it once I'm back on lab tomorrow. The first time we ran CHOMP, the UR jerked pretty hard and it stopped itself via the mechanism of the polyscope software (I imagine). So we then re-scaled the velocities (and accelerations) to 0.01 from within rviz because the first time, but the motion was really slow yet jerky and eventually timed itself out. There was a whole new message on the pendant that I hadn't seen in my last 4 months with the robot; I'll try to post shots of all of this tomorrow once I am back on lab. Just unwinding now after a fairly long day :)

**Comment by angadhn** [comment]
@bmagyar Apologies for the tardy response; somehow my super old phone flubbed up the recording and the motion was aggressive enough that we didn't have the courage to try to attempt the move again. However, I did follow thorough on the PR that @gavanderhoorn shared and presto things are smooth again. Thanks both!
