### ISSUE TITLE
Escape out a line in tutotrial formatter

### ISSUE THREAD

**Issue by Ridhwanluthra** [ros-planning/moveit#945]
### Description

Ability to escape out a couple of lines in order to not show in the tutorial

### Your environment
* ROS Distro: [Kinetic]
* OS Version: Ubuntu 16.04
* Source build

### Expected behaviour
// hey
//[some character] hey1
// hey2

output:
hey
hey2

**Comment by Ridhwanluthra** [comment]
@mlautman

**Comment by v4hn** [comment]
1. Please write in full sentences. Otherwise nobody understands what you mean.
2. This seem to be about http://github.com/ros-planning/moveit_tutorials , so it belongs there.
3. I guess there is already a way to do this, but @mlautman is the expert there.

I'll leave it to him to deal with this issue.
